# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2022 Axway Software SA and its affiliates. All rights reserved.
#
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y \
    curl \
    bash \
    netcat && \
    rm -rf /var/lib/apt/lists && \
    addgroup axway && \
    adduser --disabled-password --gecos '' --ingroup axway axway

USER axway
COPY *.sh ./

CMD [ "./run-test-pre-upgrade.sh" ]
