# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2019 Axway Software SA and its affiliates. All rights reserved.
#
before_script:
- eval export DOCKER_TAG=$CI_COMMIT_REF_NAME
- | # If we're on the master branch, tag the image as latest
  if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
    eval export DOCKER_TAG="latest"
  fi
- echo Using DOCKER_TAG=$DOCKER_TAG

stages:
- build
- test
- security
- push

build:
  stage: build
  script:
  - docker build -t cft/cft:$DOCKER_TAG .

test:
  stage: test
  script:
  - docker-compose -f docker-compose.test.yml down -v
  - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --remove-orphans --force-recreate sut
  after_script:
  - docker-compose -f docker-compose.test.yml down -v

security:
  stage: security
  script:
  # Scan the image and store the URL of the scan results
  - eval export URL=$(twistcli images scan -u $TWISTLOCK_USER -p "$TWISTLOCK_PASSWORD" --address $TWISTLOCK_URL --upload cft/cft:$DOCKER_TAG | grep scan | cut -b29-)
  - echo URL=$URL
  # Prepare Twistlock credentials
  - TOKEN=$(echo -n "$TWISTLOCK_USER:$TWISTLOCK_PASSWORD" | openssl base64)
  # Download and untar scan results. Scan results file is "analysis.json"
  - "curl -k -H \"Authorization: Basic $TOKEN\" $URL | tar xvz"
  # Upload to theadfix
  #- cat analysis.json | jq .
  - "curl --insecure -H \"Accept: application/json\" -H \"Authorization: APIKEY $THREADFIX_APIKEY\" -X POST --form file=@analysis.json https://vulnmgt.psg.axway.int/threadfix/rest/v2.5/applications/$THREADFIX_APPID/upload"
  # Remove scan results.
  - rm -f analysis.json

push:
  stage: push
  script:
  - docker tag cft/cft:$DOCKER_TAG $REGISTRY_URL/cft/cft:$DOCKER_TAG
  - docker push $REGISTRY_URL/cft/cft:$DOCKER_TAG
