# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2019 Axway Software SA and its affiliates. All rights reserved.
#
before_script:
- eval export DOCKER_TAG=$CI_COMMIT_REF_NAME
- | # If we're on the master branch, tag the image as latest
  if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
    eval export DOCKER_TAG="latest"
  fi
- echo Using DOCKER_TAG=$DOCKER_TAG

stages:
- build
- test
- security
- push

build:
  stage: build
  script:
  - docker build -t $IMAGE_CFT:$DOCKER_TAG --build-arg URL_BASE=https://delivery.axway.int/download_true_name.php?static= .

test:
  stage: test
  script:
  - docker-compose -f docker-compose.test.yml down -v
  - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --remove-orphans --force-recreate sut
  after_script:
  - docker-compose -f docker-compose.test.yml down -v

security:
  stage: security
  script:
  # Scan the image and store the URL of the scan results
  # Prepare Twistlock credentials
  - CREDENTIALS=$(echo -n "$TWISTLOCK_USER:$TWISTLOCK_PASSWORD" | openssl base64)
  # Scan the image
  - twistcli images scan -u $TWISTLOCK_USER -p "$TWISTLOCK_PASSWORD" --ci --address $TWISTLOCK_URL $IMAGE_CFT:$DOCKER_TAG
  # Retrieve the scan result
  - "curl --insecure -H \"Authorization: Basic $CREDENTIALS\" -H \"Content-Type: application/json\" -X GET \"$TWISTLOCK_URL/api/v1/scans?search=$IMAGE_CFT:$DOCKER_TAG&sort=time&reverse=true&limit=1&type=jenkins\" > analysis.json"
  - echo ">>>> analysis.json"
  - cat analysis.json | jq .
  - echo "<<<< analysis.json"
  # Upload the scan result to ThreadFix
  - "curl --insecure -H \"Authorization: APIKEY $THREADFIX_APIKEY\" -H \"Accept: application/json\" -X POST --form \"file=@analysis.json\" https://vulnmgt.psg.axway.int/threadfix/rest/v2.5/applications/$THREADFIX_APPID/upload"
  # Remove scan results.
  - rm -f analysis.json

push:
  stage: push
  script:
  - docker tag $IMAGE_CFT:$DOCKER_TAG $REGISTRY_URL/$IMAGE_CFT:$DOCKER_TAG
  - docker push $REGISTRY_URL/$IMAGE_CFT:$DOCKER_TAG
