#!/bin/sh

whoami
if [ $? -ne 0 ]; then
    if [ -w /etc/passwd ]; then
        echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
        echo "user ${USER_NAME:-default} ($(id -u)) created"
    fi
fi

exec "$@"
