apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cft
  name: cft_secrets
type: Opaque
data:
  cft.key : # Complete this, you must add the base64 conversion of the key value
            # In Linux, the base64 conversion can be done via 'cat conf/cft.key | base64'
  # To add the xfbadm password as a secret, you must uncomment the next line and add the base64 conversion
  # of the password value after the colon symbol
  #xfbadm.pwd : 
  # To add the shared_secret as a secret, you must uncomment the next line and add the base64 conversion
  # of the shared_secret value after the colon symbol
  #shared_secret :
  # To add the copilot_p12 password as a secret, you must uncomment the next line and add the base64 conversion
  # of the password value after the colon symbol
  #copilot_p12.pwd :
